<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-TechConfCentral-5d4f5e13-f554-448c-8c95-5ca093c2383e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechConfCentral.BLL\TechConfCentral.BLL.csproj" />
    <ProjectReference Include="..\TechConfCentral.Models\TechConfCentral.Models.csproj" />
  </ItemGroup>

</Project>
