// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechConfCentral.DAL;

#nullable disable

namespace TechConfCentral.DAL.Migrations
{
    [DbContext(typeof(TechConfCentralContext))]
    [Migration("20260812231849_UpdatedConferenceEndDate")]
    partial class UpdatedConferenceEndDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechConfCentral.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TechConfCentral.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Conference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "San Francisco",
                            Country = "USA",
                            Description = "The premier developer conference.",
                            EndDate = new DateOnly(2026, 11, 17),
                            Name = "DevHorizon 2026",
                            StartDate = new DateOnly(2026, 11, 15),
                            StateOrProvince = "CA",
                            Tagline = "where code meets the machine_",
                            Venue = "Pier 70"
                        });
                });

            modelBuilder.Entity("TechConfCentral.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Room", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 300,
                            Name = "Room A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 250,
                            Name = "Room B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 150,
                            Name = "Room C"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 150,
                            Name = "Room D"
                        });
                });

            modelBuilder.Entity("TechConfCentral.Models.SavedTalk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TalkId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TalkId");

                    b.HasIndex("UserId", "TalkId")
                        .IsUnique();

                    b.ToTable("SavedTalk", (string)null);
                });

            modelBuilder.Entity("TechConfCentral.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Speaker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Elena has spent the last decade pushing the boundaries of in-browser development environments. She led the browser-native IDE initiative at Bytecraft and is a frequent contributor to the TC39 process. Her work focuses on making the web platform a first-class development target.",
                            Company = "Bytecraft",
                            FirstName = "Elena",
                            IsFeatured = true,
                            JobTitle = "Principal Frontend Engineer",
                            LastName = "Vasquez",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Dinesh is a senior frontend engineer at Pied Piper, where he led the development of the Pied Piper video chat platform and the consumer-facing web interface. He specializes in real-time video compression on the client side and has deep experience with WebRTC, codec optimization, and building performant media experiences in the browser.",
                            Company = "Pied Piper",
                            FirstName = "Dinesh",
                            IsFeatured = false,
                            JobTitle = "Senior Frontend Engineer",
                            LastName = "Chugtai",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 3,
                            Biography = "James oversees Cartwell's frontend platform team, managing the monorepo that powers thousands of internal and merchant-facing applications. He's a vocal advocate for developer experience as a product concern and has led the company's migration to a unified build system serving over 300 engineers.",
                            Company = "Cartwell",
                            FirstName = "James",
                            IsFeatured = true,
                            JobTitle = "Engineering Director",
                            LastName = "Okonkwo",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Mei-Lin is a CSS Working Group invited expert and the architect behind Roamly's responsive design system. She's been a leading voice in the container queries specification process and has helped ship container query-based layouts to production.",
                            Company = "Roamly",
                            FirstName = "Mei-Lin",
                            IsFeatured = false,
                            JobTitle = "Staff Engineer",
                            LastName = "Zhang",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Priya works on the developer relations team at Cobalt, focusing on accessibility tooling and standards education. She created the popular 'A11y Myths Busted' video series and contributes to the browser's accessibility auditing rules.",
                            Company = "Cobalt",
                            FirstName = "Priya",
                            IsFeatured = true,
                            JobTitle = "Senior Developer Advocate",
                            LastName = "Sharma",
                            ProfileImage = ""
                        });
                });

            modelBuilder.Entity("TechConfCentral.Models.Talk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsKeynote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("TrackId");

                    b.ToTable("Talk", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConferenceId = 1,
                            Description = "The opening keynote. Elena takes the audience on a tour of the web platform's most transformative recent additions — from WebGPU to View Transitions to baseline support for container queries. She live-demos a full-stack application running entirely in the browser and makes the case that the gap between native and web has never been smaller.",
                            EndDateTime = new DateTime(2026, 11, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            IsKeynote = true,
                            RoomId = 1,
                            SpeakerId = 1,
                            StartDateTime = new DateTime(2026, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Next Frontier of Web Development",
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConferenceId = 1,
                            Description = "Modern video compression on the web is stuck between bloated codecs and unacceptable quality tradeoffs. Dinesh presents Pied Piper's middle-out compression approach adapted for browser-based video delivery — achieving dramatically better compression ratios without sacrificing visual fidelity.",
                            EndDateTime = new DateTime(2026, 11, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            IsKeynote = false,
                            RoomId = 2,
                            SpeakerId = 2,
                            StartDateTime = new DateTime(2026, 11, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Video Compression for the Web: The Middle-Out Approach",
                            TrackId = 3
                        },
                        new
                        {
                            Id = 3,
                            ConferenceId = 1,
                            Description = "Cartwell's frontend monorepo contains over 500 packages, dozens of apps, and is contributed to by 300+ engineers daily. James shares the hard-won lessons from building and maintaining this system — from dependency management and build caching to code ownership and migration strategies.",
                            EndDateTime = new DateTime(2026, 11, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            IsKeynote = false,
                            RoomId = 4,
                            SpeakerId = 3,
                            StartDateTime = new DateTime(2026, 11, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Monorepos at Scale: Lessons from 500 Packages",
                            TrackId = 5
                        },
                        new
                        {
                            Id = 4,
                            ConferenceId = 1,
                            Description = "Container queries have shipped in every major browser, but adoption in production remains low. Mei-Lin shares Roamly's journey of replacing hundreds of JavaScript-based responsive components with pure CSS container queries.",
                            EndDateTime = new DateTime(2026, 11, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            IsKeynote = false,
                            RoomId = 1,
                            SpeakerId = 4,
                            StartDateTime = new DateTime(2026, 11, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CSS Container Queries in Production",
                            TrackId = 2
                        },
                        new
                        {
                            Id = 5,
                            ConferenceId = 1,
                            Description = "Well-intentioned ARIA usage often makes interfaces less accessible, not more. Priya walks through the most commonly misused ARIA roles and properties — live regions that fire too often, menu roles on navigation, dialog traps that trap too much — and shows how to audit and fix them.",
                            EndDateTime = new DateTime(2026, 11, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            IsKeynote = false,
                            RoomId = 3,
                            SpeakerId = 5,
                            StartDateTime = new DateTime(2026, 11, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ARIA Patterns You're Probably Using Wrong",
                            TrackId = 4
                        });
                });

            modelBuilder.Entity("TechConfCentral.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Track", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#B5E9FC",
                            Description = "Opening and closing sessions",
                            Name = "Keynote"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#FFE6BA",
                            Description = "Building modern interfaces for the web",
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FEC9C3",
                            Description = "Make every millisecond count",
                            Name = "Performance"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#BBD8FF",
                            Description = "Building inclusive experiences for everyone",
                            Name = "Accessibility"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#CCC4FD",
                            Description = "Level up your developer workflow",
                            Name = "Tooling"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechConfCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechConfCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechConfCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechConfCentral.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechConfCentral.Models.SavedTalk", b =>
                {
                    b.HasOne("TechConfCentral.Models.Talk", "Talk")
                        .WithMany("SavedTalks")
                        .HasForeignKey("TalkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechConfCentral.Models.ApplicationUser", "User")
                        .WithMany("SavedTalks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechConfCentral.Models.Talk", b =>
                {
                    b.HasOne("TechConfCentral.Models.Conference", "Conference")
                        .WithMany("Talks")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechConfCentral.Models.Room", "Room")
                        .WithMany("Talks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechConfCentral.Models.Speaker", "Speaker")
                        .WithMany("Talks")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechConfCentral.Models.Track", "Track")
                        .WithMany("Talks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conference");

                    b.Navigation("Room");

                    b.Navigation("Speaker");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TechConfCentral.Models.ApplicationUser", b =>
                {
                    b.Navigation("SavedTalks");
                });

            modelBuilder.Entity("TechConfCentral.Models.Conference", b =>
                {
                    b.Navigation("Talks");
                });

            modelBuilder.Entity("TechConfCentral.Models.Room", b =>
                {
                    b.Navigation("Talks");
                });

            modelBuilder.Entity("TechConfCentral.Models.Speaker", b =>
                {
                    b.Navigation("Talks");
                });

            modelBuilder.Entity("TechConfCentral.Models.Talk", b =>
                {
                    b.Navigation("SavedTalks");
                });

            modelBuilder.Entity("TechConfCentral.Models.Track", b =>
                {
                    b.Navigation("Talks");
                });
#pragma warning restore 612, 618
        }
    }
}
